pipeline {
  agent any
  parameters {
    string(name: 'PROJECT_PATH', defaultValue: 'Infra/FCMS')
    string(name: 'ACCOUNT', defaultValue: '490472793553')
    string(name: 'REGION', defaultValue: 'ap-northeast-2')
    string(name: 'VPC_ID', defaultValue: 'vpc-01c272f54dc314fd9')
  }
  options {
    disableConcurrentBuilds()
  }
  tools { nodejs 'node-14-15-0' }
  stages {
    stage('deploy') {
      steps {
        script {
          def script = "./jenkins/jobs/ngrinder/script.sh"
          withAWS(region:"${params.REGION}",credentials:'aws-access')\
          {
              dir("${params.PROJECT_PATH}"){
                sh "chmod +x ${script}"
                sh "${script} ${params.ACCOUNT} ${params.REGION} ${params.VPC_ID}"
              }
          }
        }
        cleanWs()
      }
    }
  }
}